const STATUS_DATA_LOADING = 'LOADING';
const STATUS_DATA_ACTIVE = 'ACTIVE';
const STATUS_DATA_FAILED = 'FAILED';
const STATUS_DATA_INITIAL = 'INITIAL';

export {
  STATUS_DATA_LOADING,
  STATUS_DATA_ACTIVE,
  STATUS_DATA_FAILED,
  STATUS_DATA_INITIAL,
};
